### ISSUE TITLE
Change static file server prefix

### ISSUE THREAD

**Issue by Immortalin** [franciscop/server#100]
How do you change the prefix of the static file path from "/"?

**Comment by franciscop** [comment]
You could create a folder inside `public` with the name you want. Example: for `/demo` create the folder `public` and inside it the folder `demo`. Then the URL `/demo/a.jpg` will point correctly to the path `./public/demo/a.jpg`.

For the other way around you can use the option `public` to select what folder to consider the root.

There is no equivalent to express' `app.use('/path', express.static(...))` though, because server tries to keep these kind of things with as little middle layers as possible.
