### ISSUE TITLE
How big can it scale?

### ISSUE THREAD

**Issue by elieobeid7** [franciscop/server#115]
On the website it says that the project is suitable for small to medium size projects.

- How many concurrent users does that mean?
- Is it possible to scale it up easily?
- Is anyone using it in production?

**Comment by vorticalbox** [comment]
So the amount of users it can handle is based mostly on your code.

When your JavaScript is running the event loop isn't so if you have routes that use up a lot of CPU time the latency will increase for all other requests.

If a route has blocking code such as a for loop that loops lots of items from a dB and takes 1 second to complete any other requests will have to wait at least 1 s.

The trick is to have multiple copies of your server running and use a proxy to route traffic to the processes. This is how you scale node.

I used this in production to save items to a database but it's since been replaced by a lambda :(

**Comment by elieobeid7** [comment]
Thank you so much.

**Comment by franciscop** [comment]
- How many concurrent users does that mean?

This normally depends on your code more than the framework itself. If I remember correctly, last time I checked in my laptop server.js could handle 8-10k rps, but it was just a sanity check and not a proper benchmark. In contrast, with a similar test, express.js could take 12-13k rps and the raw Node.js 18-20k rps.

- Is it possible to scale it up easily?

Never needed to, not even under "heavy" peak HN+ProductHunt load. But reverse proxy and multiple processes seems like the normal approach, which should be perfectly possible.

- Is anyone using it in production?

Thousands of people download it per week, but unfortunately I do not know who. I'm using it in several personal projects live.
