### ISSUE TITLE
Why npmlog?

### ISSUE THREAD

**Issue by aqeelat** [franciscop/server#158]
Since npmlog is no longer maintained, why not use an alternative library such as consula or pino?

**Comment by franciscop** [comment]
Because unfortunately that'd be a subtle breaking change for those using Server, and I'm trying to maintain `server` without changing the API too much. Is there any known vulnerability in npmlog? It seems very stable, but if there was some I'd be happy to reconsider.

Note: I'm also working now so I cannot dedicate fulltime to actively develop my projects, only maintain them. When I do get some time to do some new dev I'm also doing on https://server-js.com/ on the side, which as noted there right now is highly experimental but I'm hoping some day becomes the next Server code/library.
