### ISSUE TITLE
can not log 'ctx'

### ISSUE THREAD

**Issue by b5156** [franciscop/server#16]
i just run :
`server({ port: 8080 }, [
  get('/abc', ctx =>{console.log(ctx)}),
]);`

but error:

 'Cannot convert a Symbol value to a string',

nodejs : v8.2.1

**Comment by franciscop** [comment]
Thanks for pointing out this issue, I had seen it previously. **Could I ask what is the main reason for you doing this?** Is it finding out `ctx` properties?

If you want to know the keys you could do this until I get around fixing it:

```js
server({ port: 8080 }, [
  get('/abc', ctx => { console.log(Object.keys(ctx)); })
]);
```

I just also documented the properties more in-depth [on the Context documentation](https://serverjs.io/documentation/context/) (note: first draft).

I cannot give an estimate on when I will fix it since I might need to change some fundamental things first, but since this seems to be something that could become a common issue I'll get it fixed ASAP.

**Comment by franciscop** [comment]
Hi @b5156, I think this should be fixed in the Beta 3. Please upgrade and let me know whether it is fixed or not.
