### ISSUE TITLE
Nested Routes

### ISSUE THREAD

**Issue by chameleonbr** [franciscop/server#18]
Hello, do you have plans to include "use" method on router?
This way we could create nested routes, example:

```javascript
//products.js
const {get, post, del} = require('server/router')
module.exports = [
get('/',ctx=>{return "products"}),
get('/:id',ctx=>{return "product"}),
post('/',ctx=>{return "product"}),
del('/:id',ctx=>{return "product"}),
]

//index.js
const server = require('server')
const { use } = server.router
server([
use('/products',require('./products'))
])
```
This would do the same effect as the express router, creating sub routes hierarchically.
Thanks for the project, I really enjoyed it.

**Comment by franciscop** [comment]
Hi @chameleonbr , I thought about this a lot before deciding *not* making this the default behaviour of the routes. The main points:

## Predictability 

The route that you see is the route that you get. It is somewhat common to see this in projects to make it more clear what is going on:

```js
// ...
module.exports = [
  // /products/
  get('/', ...),

  // /products/:id/whatever
  get('/:id/whatever', ...)
];
```

Which totally defeats the purpose of having the path automatically generated like in express. So I strongly prefer routes that make it clear what is going on:

```js
// ...
module.exports = [
  get('/products', ...),
  get('/products/:id/whatever', ...)
];
```

## Obsolete

I can also see how this can be somewhat useful to change a bunch of them at once and in a single place. However, with any text editor, you can select all of the `/products/` parts, or just `Replace all` in a single file easily. So the repetition argument for this exact situation is not so strong as it could be or as in other kind of code repetition IMHO.

## Modules

However it is true that this puts us in disadvantage when creating an external package. Maybe you want to use an external middleware library and put the whole thing in a subpath. Right now that is not possible, and it's a limitation. But I think it's a small limitation compared to the benefit of being more predictable and that is why I decided to ultimately do it this way.


## Proposal

Now, you are not proposing to make all nested routes to behave like this, just create a new `use()`. It might be a good compromise, but I don't dig the name. Maybe it would be better with `path()*` or `root()` or something like this. `use()` with this behaviour would hint too strongly that other routes behave similar to express, when they do not, so changing the name to something more explicit would be better.

But right now there are some other much higher priorities than supporting the specific situation that I outlined. For your specific situation with internal code, I'd recommend to make it explicit.

*`path()` might not be the best name since it'd easily conflict with `const path = require('path');`

**Comment by chameleonbr** [comment]
I understood your point of view, but we use "Router use" because we can delegate the routes that the developer can build, either in the project itself or outside (modules), when you have a bigger project this can be interesting.

In Express you can use either a middleware or a router, establishing sub routes or not, this makes it much easier to include external modules.

I hope someday there will be interest in developing this functionality.
Bye.
