### ISSUE TITLE
Cannot find module 'server/test/run'

### ISSUE THREAD

**Issue by bodhisattva082915** [franciscop/server#31]
Installed server.js and have loved it so far. Really easy to get setup and a lot of simple conveniences that you don't get from straight-up express. I'm now wanting to write a test suite, but it's looking like the test folder doesn't exist in the source files. 

I installed via npm and am running at v1.0.1. 
Listing the contents of the node_modules folder shows that test is missing.

`root@2f31a5645e01:/usr/app/node_modules/server# ls`
`Contributing.md  Gruntfile.js  LICENSE  README.md  api.js  appveyor.yml  circle.yml  coverage  error  package.json  plugins  reply  roadmap.md  router  server.js  src`

**Comment by franciscop** [comment]
I see that in the documentation I published both the Errors and Test pages. I am sorry about that, they were never meant to be published since they are not mature yet nor should have been officially launched (that is what the red points mean).

For this reason `server/test` is not published as shown in the `.npmignore`. While I could publish it, I think it'd only burden you when I change/improve it to make it more production-ready and break your system.

How do you want to test your code? What were your intentions for `run()`? Please feel free to copy `test/run.js` and `test/port.js` from the codebase into your project, but then you'll have to treat it as your own code and maintain it yourself.

**Comment by bodhisattva082915** [comment]
I was just wanting to have the convenience of the run() method for API testing. For now I'll just roll my own suite, manually setting up the a mock server, with mocha/chai until the testing portion is production ready.
