### ISSUE TITLE
Best way to emit socket.io events not triggered by a request

### ISSUE THREAD

**Issue by henninghorn** [franciscop/server#48]
I've read the [real-time tutorial](https://serverjs.io/tutorials/chat/) and I've build my own with absolute no problems at all.

But I'm unsure about how to emit events through socket.io that isn't triggered by a request, unlike in the chat tutorial.

Currently I'm trying to figure out how to emit tweets as they come in via the [twit package](https://www.npmjs.com/package/twit).

What is the best way to get hold of `ctx.io` so that I can call `ctx.io.emit('tweet', tweet)`?
Or how do you independently of a request emit an event through socket.io from the server?

My current "solution" is this:
```js
// [...]
var streamActive = false

const startStream = ctx => {
  if (streamActive) return
  streamActive = true

  const stream = T.stream('statuses/filter', { track: 'apple' })
  stream.on('tweet', tweet => {
    ctx.io.emit('tweet', tweet.text)
  })

}

server([
  socket('connect', startStream)
])
```

**Comment by franciscop** [comment]
I see the issue. I think it'd be easier when the server is launched as you get access to io:

```js
const startStream = ctx => {
  const stream = T.stream('statuses/filter', { track: 'apple' })
  stream.on('tweet', tweet => {
    ctx.io.emit('tweet', tweet.text)
  })
  return ctx;  // Highly recommended to make it chainable
}

server(ctx => 'Hello world').then(startStream)
```

The whole `server()` will give back a promise that will resolve when the server is launched and listening. Note that this context (might as well be called `instance`) has a much smaller API and will add some properties through the plugins, but not all since it is not in any request path. `.io` [gets added here](https://github.com/franciscop/server/blob/master/plugins/socket/index.js#L15) and will be available for any kind of `ctx`.

Does that work for you?

***


How would you think could be a good way to make it work otherwise? I was thinking about two possibilities for the future:

```js
// Possibility 1; using plugins:
server({
  init: ctx => {
    // this code will be run just once
  }
});

// Possibility 2; using a special router:
server(once(ctx => {
  // this code will also be run only once
}));
```

However both of those feel a bit clunkier and more confusing than the answer I gave you for this specific situation.

**Comment by michaeljota** [comment]
As I post in #37, the object returned from the resolved server promise have a `io` property that you could use to send message from anywhere.

**Comment by henninghorn** [comment]
Thank you for the quick response, @franciscop 

I hadn't read about the promise returned by `server`.
I think this approach is good. Between the two solutions you proposed, I would go for special `once` route approach.

Once a again, thank you for your quick response. Keep up the great work on this project!

**Comment by michaeljota** [comment]
I think that's not on the docs yet. You just have to digg a little in the code. (Documented, well written)
