### ISSUE TITLE
http request method OPTIONS

### ISSUE THREAD

**Issue by paulrobello** [franciscop/server#58]
I am trying to get an ajax post from a browser to work and its getting a 404 back when its sends the preflight OPTIONS check.
I don't see anything document on OPTIONS request types.
I have the post route defined. and it works if there is no preflight-check.

**Comment by franciscop** [comment]
Hi Paul, I see that [you are doing the CORS manually](https://github.com/franciscop/server/issues/55#issuecomment-354581929). If you use the `cors` package it will take care of the preflight automatically, so [I'd recommend using `cors()`](https://serverjs.io/documentation/#cors):

```js
const server = require('server');
const expressCors = require('cors');

// Load cors and make it usable as a server middleware
const cors = server.utils.modern(expressCors());

// Launch the server with this specific middleware
server({}, cors, ...);
```

Otherwise, and based [on this SO answer](https://stackoverflow.com/a/46028619/938236), you could do:

```js
const preflight = ctx => {
  if (ctx.method === 'OPTIONS') {
    return 200;
  }
};

server({}, preflight, ...);
```

Be aware that this will still match any other middleware that is not routed as expected, so to avoid it make sure your routes are routed with `get()`, `post()`, etc:

```js
server({}, preflight, ctx => { console.log('I *do* get logged'); });
```

I will make sure to document this, since the documentation for that is incomplete ATM. Please let me know if that fixes it and thanks again for using server.js and posting a bug!

**Comment by franciscop** [comment]
BTW, do you want to do a video/screensharing call? I can help you fix any issues that you might be facing with server.js or Node.js in general, and at the same time learn more about how other devs like you are using server.js (which will also help me improve it).

**Comment by paulrobello** [comment]
Using the cors package fixed my issue. Once again thank you for your help.
My project is a link / bookmark sharing website that supports real time updates using websockets and rethinkdb change feeds. It also has a corresponding chrome plugin for easy link sharing. 
I would me more than happy to screen / code share. 
It is still very alpha as I am still feeling out how I ultimately want to build out the gui / feature set.
PM or email me any time.
