### ISSUE TITLE
How to access the server listener to handle server autoreload?

### ISSUE THREAD

**Issue by cloud-walker** [franciscop/server#61]
Hi, I work with webpack and universal applications, and my express server is hot reloaded by webpack during development, I'm wondering how I can achieve the same feature using `server`.

This is my entry server file:
```javascript
import http from 'http'

import app from './expressInstance'

const server = http.createServer(app)

let currentApp = app

server.listen(process.env.PORT || 3000)

if (module.hot) {
  console.log('✅  Server-side HMR Enabled!')

  module.hot.accept('./expressInstance', () => {
    console.log('🔁  HMR Reloading `./expressInstance`...')
    server.removeListener('request', currentApp)
    const newApp = require('./expressInstance').default
    server.on('request', newApp)
    currentApp = newApp
  })
}
```

As you can see I can use http module to create a server and manipulate the listeners to swap the express application on the fly during development.

**Comment by franciscop** [comment]
I have never seen anything like this. Would something like this work?

```js
const server = require('server');

// Import index.js
const { options, middleware } = require('./');

server(options, middleware).then(inst => {
  if (module.hot) {
    module.hot.accept('./', async () => {
      await inst.close();
      const { options, middleware } = require('./').default;
      inst = await server(options, middleware);
    });
  }
});
```

**Comment by cloud-walker** [comment]
I will try out ASAP and I will tell you, thank you!

**Comment by cloud-walker** [comment]
Hi, playing with your proposal I end up with a "working" version:

```javascript
import server from 'server'

import middleware from './middleware'

const init = () =>
  server({port: process.env.PORT}, middleware()).then(inst => {
    if (!module.hot) {
      return
    }

    console.info('✅  Server-side HMR Enabled!')

    module.hot.accept('./middleware', async () => {
      console.info('🔁  HMR Reloading `./middleware`..')
      await inst.close()
      init()
    })
  })

init()
```

But I'm not sure about memory leaks: I close the server instance, and "replaying" the same promise again every time I make a change on the middleware code 🤔 

Its ok? Or maybe I have to clean up something?

**Comment by franciscop** [comment]
It looks like it's going to leak memory, but for production you don't need the hot module reloading, do you?

```js
// reload.js => for hot reloading
your code
```

```js
// index.js => production
const middleware = require('./middleware');
require('server')(middleware);
```

Tip: you do not need `{ port: process.env.PORT }`, [this is the behaviour by default](https://serverjs.io/documentation/options/#port).

Of course the ideal would be fixing the leaks. But since you will be taking breaks hopefully at least once daily, it is probably fine to have the leaking one in dev and the fixed one in prod. Make sure the automated tests run on the production one with your CI/CD. Also, even if you deploy the leaky version, as explained I think you won't be doing HMR in production anyway.

For memory leaks, what you want to do in general is to remove recursion (creating an instance inside the closing of the old one) and instead replace the old instance with the new one.

Hope I was of some help :smiley:
