### ISSUE TITLE
Handle 404 errors

### ISSUE THREAD

**Issue by vorticalbox** [franciscop/server#62]
### Description

Currently you need to define each router to added 404 errors
`
get(ctx => status(404))
post(ctx => status(404)
put(ctx => status(404)
`

### Expected outcome

If the request going to an undefined route return 404 status  

### Actual outcome

500 internal error 

### System Information

**OS:** Windows 10

**Node Version:** v8.9.3

**Comment by franciscop** [comment]
It should be returning a `404` if nothing was matched [from the `final` plugin](https://github.com/franciscop/server/blob/master/plugins/final/index.js#L11):

```js
// Internal note: update it for server.js' Reply
ctx.res.status(ctx.res.explicitStatus ? ctx.res.statusCode : 404).send();
```

A 500 sounds like something else is failing and the [error handler is being called](https://github.com/franciscop/server/blob/master/plugins/final/index.js#L21). Could you share more information please? If you write this in the end, does it log anything useful?

```js
const { error } = require('server/router');

server(

  // ...

  error(ctx => { console.log(ctx.error); })
);
```

Do you see any error in the console?

**Comment by vorticalbox** [comment]
Ok I just noticed it throws 404 status back to postman sorry. could we get a server option added something like

`{
    404: {
        //return a json message on 404
        json: {message: '404 rpute not found'},
        //return a page
        page: './views/404.pug'
    }
}`

only one can be used, this would allow for custom messages or pages with the 404 without as I did in the OP catching every single one.

**Comment by franciscop** [comment]
My answer was never sent (and actually lost!), sorry. So, instead of the proposed option, you can do this now:

```js
server(
  // normal routes
  // ...

  // 404 route (hasn't been matched)
  get(ctx => json({ message: '404 route not found' }))
);
```

It is similar in amount of code but you don't need to learn a new option for error messages. This has the advantage that you can choose the response type easily. Just `json` in your proposed context would be ambiguous, since it could mean:

- The request was made with AJAX, so it expects some json back: `ctx => ctx.xhr`.
- The request sent some JSON, so it expects some JSON back `Content-type: application/json`.
- The request accepts some JSON, so send the JSON `Accept: application/json`.

So it is better to leave the devs using server() to make this decision. If you are worried about repetition:

```js
const notFound = ctx => json({ message: '404 route not found' });

server(
  // normal routes
  // ...

  // 404 routes (haven't been matched)
  get(notFound), post(notFound), put(notFound), del(notFound)
);
```

**Comment by franciscop** [comment]
About it logging a 500, it is only in the console since this is the default error status, in the browser it should be a 404 as you found out. I have it fixed in my code, will be packed in the next minor dev version.
