### ISSUE TITLE
Restarting server on changes

### ISSUE THREAD

**Issue by karneaud** [franciscop/server#71]
### Description

Is there anyway to start/ stop/ restart the server during test?

### Expected outcome

to start separate server to run jasmine tests then stop the server after test complete

### Actual outcome

Not sure how to stop server other than usual `CTRL + C` command

**Comment by SidneyNemzer** [comment]
Good question, I actually was wondering about this myself. I don't think it's in the documentation at the moment.

I did discover that there's a `close` function on the `ctx` object from the main function:

```javascript
server( /* middleware */)
  .then(ctx => {
   ctx.close() // in this context, it will instantly close the server, but hopefully you get the idea
  })
```

@franciscop I would be great if this `close` function was documented!

**Comment by franciscop** [comment]
**To answer your questions**, yes there is as @SidneyNemzer mentioned. However **this is not a production-ready method and might change in the future**, so please use with care (note: it will probably not change, but only the documented API should be considered stable).

However please note that `close()` will return a callback:

```js
server().then(async ctx => {
  // do something...
  await ctx.close();
  // now it is closed! without the await it might not yet have closed
  // Note: if a websocket is connected it won't close, see the socket plugin tests :(
});
```

***

# Testing in server.js

The main problem is that you cannot launch it twice in the same port and jest runs the tests in parallel. Now, that is solved for internal tests. If you look at the internal tests, I am using a function called `run()` that comes from `test/run.js`:

```js
it('loads the homepage', async () => {
  const options = {};
  const routes = [() => 'Hello world'];
  const res = await run(options, routes).get('/');
  expect(res.status).toBe(200);
});
```

It works quite great for testing server (and that is why I created it). However, I want to release it at some point, possibly for 1.1 with the plugins, but there are two blocking issues right now:

## 1. It doesn't accept an instance

When running tests over your actual code you probably want to run those against the running server, not against server itself. this means doing something like this:

```js
// index.js
module.exports = server(options, routes);
```

```js
// index.test.js
const instance = require('./index');

it('can load the homepage', async () => {
  const res = await run(instance).get('/');
  ...
});
```

But it doesn't work properly yet, with the plugins being the main culprit here. The plugins are changing and they will be able to register a `listen()` (or `launch()`) and a `close()` each, as in websockets. This is work in progress right now.

> To fix this the specification for the plugins have to be finished first. This spec is my main focus right now, but unfortunately I am not documenting it much.

## 2. Long-lived sessions

This is even more blocking and difficult, you probably want to test long-lived sessions or at least websockets, which is not possible now at all. I am working on this with something like this, but it is still really buggy:

```js
// index.test.js
run(options, routes).alive(async api => {
  const res = await api.get('/');
  expect(...);
  await api.post('/login', ...);
  // etc
});
```

There are many open-ended questions here: what about cookies and sessions?  What about websockets? What about...


## Conclusion

As soon as I figure out how to fix these two issues and test it enough, I will release `run` for production, with its documentation and tests.

**Comment by karneaud** [comment]
Cool. Since I'm using web pack I'm looking at some alternatives using node request package and nodemon. kind of heavy but i'm not familiar with your software at the moment to see anything else that could be done.

**Comment by franciscop** [comment]
Sure, that should work:

```js
server(...).then(ctx => {
  request(`http://localhost:${ctx.options.port}/`);
});
```

**Comment by franciscop** [comment]
Sure, that should work:

```js
server(...).then(ctx => {
  request(`http://localhost:${ctx.options.port}/`);
});
```

**Comment by mindplay-dk** [comment]
> To answer your question, yes there is as @SidneyNemzer mentioned. However **this is not a production-ready method and might change in the future**, so please use with care (note: it will probably not change, but only the documented API should be considered stable).
> 
> However please note that `close()` will return a promise
>
> ...
> 
> ## Conclusion
> As soon as I figure out how to fix these two issues and test it enough, I will release `run` for production, with its documentation and tests.

What's the status on this one?

I just discovered server.js and immediately loved the elegant, minimal API - looks perfect for testing on my project, and frankly I'd prefer not to mess around with `express`, either by itself, or by breaking into the implementation details of server.js.

I looked everywhere in the manual for some way to stop a server - but `context.close()` remains undocumented 3 years later?

There is a list of useful issues and caveats in this issue - these would make good work items... and the issue doesn't appear to have been (officially) resolved, so I would suggest to reopen this, if you wouldn't mind?

**Comment by franciscop** [comment]
So I had big plans for Server.js (large overhauls, big plugin system) but then started working fulltime in a demanding job so now it's in maintenance[1]. Everything there should work, but I'm not rewriting/making large changes to it for the time being. I still do [some experiments](https://www.npmjs.com/package/@server/auth) from time to time.

One large issue with server.js is that I never thought too well is how devs would test their apps running this library. I've since learned and in my recent projects [I even include examples for testing](https://crossroad.page/documentation#testing-routes).

Another thing is that, when I eventually build server.js 1.1 or 2.0, I want the APIs to be mostly backwards compatible (even if 2.0 implies breaking changes, I'm trying to minimize those). So any API that I'm not completely sure, I think it's best not to have it officially supported.

So yeah, you can definitely use `server().then(ctx => ctx.close())` if you want; I'm using it in fact, but I'm not comfortable making that single function official until there's a whole story on testing. In fact, there are two large parts that are unfinished, one is testing and another is error handling (or better said, the documentation about error handling):

- [Unfinished, outdated docs about **testing**](https://serverjs.io/documentation/testing/).
- [Unfinished, outdated docs about **errors**](https://serverjs.io/documentation/errors/)

That said, I just added a small note in [Advanced Topics](https://serverjs.io/documentation/#advanced-topics) about `server().then(app => app.close())` (and named it `app` to avoid confusing it with the normal middleware context).

[1] The main reason, while I've been doing other projects, is scale. Server.js (along with probably Picnic CSS) is probably the largest and most complex project I've built. To do small but important new features/changes it takes dozens of hours (I am very strict on not breaking things in this project), which I still do (see the new [`head()` method](https://serverjs.io/documentation/router/#head-)), and to give the love the project needs to be 1st class it'd require few months of full time work IMHO. I simply don't have that time/energy right now, I hope to have it in the future but as right now I'm just doing my best to maintain the project.
