### ISSUE TITLE
Server is not setting session cookies

### ISSUE THREAD

**Issue by paulrobello** [franciscop/server#72]
Running latest from npm I have a simple GET route and the server response does not contain any cookies.
The next weird part is. Since the browser gets no cookie its not sending any cookie, however I have a simple visit counter setup in the session and it appears to increment with each visit regardless of using multiple browsers. 
The server seems to be keeping some kind of shared session which it uses for any client that does not provide a session cookie. 

The next odd thing is I have Redis setup for sessions and have confirmed the server is connected to Redis however if I restart the server the visit counter is lost. 

I am at a loss as how to debug this one....

**Comment by SidneyNemzer** [comment]
Could you please add a link to the code in question? It's difficult to guess what you might have written!

**Comment by paulrobello** [comment]
Running node v9.3.0 on Windows 10 x64
I have created a repo with a project the exhibits the issue
https://github.com/paulrobello/ServerTest

**Comment by franciscop** [comment]
I saw some issues in the auth plugin I am making but assumed it were strictly related to the plugin. Please let me dig deeper into this issue.

**Comment by franciscop** [comment]
I can confirm that it sends the cookie on `1.0.17` but it doesn't seem to work on the `1.1.0-alpha.1`. The biggest scare (and would have been a huge security issue) though is the shared session, which does not happen on the 1.0.17 and there it separates sessions properly.

I use alphas as *very* experimental releases, specially the first ones. Normally for cross-project debugging; I'll release a new alpha, install it in a couple of projects and test that everything works as expected.

So my recommendation is to use the stable ones if you want to get anything done. If you want to help me, probably the best would be beta versions. Alphas are in a broken state most of the times. But thanks for the bug report, it is definitely a high priority bug! And one that is not caught by any test, so I will leave this open until there is a test and it is fixed. (note: I just released 1.1.0-alpha.2 to see if it was fixed by any chance but that is still broken).

**Comment by paulrobello** [comment]
When you do an "npm install server" you get the broken alpha version. I am not sure how you mark a package as unstable in npm but i think it would be a good idea so that new users of your package dont get the broken ones.

**Comment by franciscop** [comment]
Really??? Thanks for letting me know, that is certainly big cause of concern. I am reading these awful notes: https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420

I think I fixed it. It was about having `server.session` available (needed for some store hooks) AND about the default context extending `server`. So the same instance of `session` was being used for everyone. I'll publish ASAP for furyher testing.

**Comment by franciscop** [comment]
Everything should be fixed, `npm install server` installs the 1.0.x version now and the session issue seems to fixed on alpha 3. Just a regression left that @SidneyNemzer pointed out.
