### ISSUE TITLE
How to access ENV variables like "REMOTE_ADDR"?

### ISSUE THREAD

**Issue by coderam** [franciscop/server#77]
Hi Francisco,

How do you access environmental variables in a "get()" request:

it would be cool to do something like:     console.log(server.ENV.REMOTE_ADDR);

get('/', ctx => {
    console.log(server.ENV.REMOTE_ADDR);
    return redirect('/index.html');
  }), 

Thanks,

**Comment by SidneyNemzer** [comment]
You can use `process.env`, right?

```
get('/', ctx => {
  console.log(process.env.REMOTE_ADDR);
  return redirect('/index.html');
})
```

**Comment by franciscop** [comment]
Exactly, this can be easily done with `process.env.NAME_OF_VAR` as @SidneyNemzer suggests 

Note that you can only access these *after* including `require('server');`, since they are being loaded there internally with dotenv. Inside the routes it'll be always okay, but on the root level you have to be a bit more careful.

**Comment by SidneyNemzer** [comment]
> Note that you can only access these after including `require('server')`

Good to know!
