### ISSUE TITLE
Context.locals is undefined

### ISSUE THREAD

**Issue by dannluciano** [franciscop/server#84]
### Description

Server not setup ```ctx.locals```

```js
const server = require('server')

const {get, error} = server.router
const {status} = server.reply

server(
  ctx => { ctx.locals.username = 'franciscop' },
  get('/', ctx => `Username is: ${ctx.locals.username}`),
  error(ctx => status(500).send(ctx.error.message))
)
```

### Expected outcome

When I access http://localhost:3000/ I should get:

```Username is: franciscop```

### Actual outcome
But when I access http://localhost:3000/ I got:

```Cannot set property 'username' of undefined```

### Live Demo

Example: https://glitch.com/edit/#!/join/17c45851-d9ac-4e98-a912-305f8e4b4dc6 

### System Information

**OS:** Windows 10

**Node Version:** v8.9.4

**Server.js Version:** 1.0.18

**Comment by franciscop** [comment]
Do you happen to know if this same code worked in a previous version? If so, do you happen to know which one? I cannot find any reference in the docs to `ctx.locals` and even the internal plugin `csurf` is using `ctx.res.locals.csrf = ctx.csrf;`, so I am wondering whether this worked before at all or not.

However, I can confirm this doesn't work now and I will fix it ASAP since this **is** the expected behaviour. Meanwhile you can use `ctx.res.locals` and it works as expected:

```js
const server = require('server')

const {get, error} = server.router
const {status} = server.reply

server(
  ctx => { ctx.res.locals.username = 'franciscop' },
  get('/', ctx => `Username is: ${ctx.res.locals.username}`),
  error(ctx => status(500).send(ctx.error.message))
)
```

**Comment by dannluciano** [comment]
Thanks @franciscop .After a little search, I cannot find any reference for ```ctx.locals``` in the source code. 
I agree with you that ```ctx.locals``` are best than ```ctx.res.locals```.
I think that *express* parts have been hidden.

**Comment by franciscop** [comment]
It should be fixed in the alpha 8, could you please try it and let me know how it works?

```bash
npm install server@next
```

**Comment by dannluciano** [comment]
This works now.
