### ISSUE TITLE
How to stream audio files

### ISSUE THREAD

**Issue by karneaud** [franciscop/server#88]
### Description

I'm trying to stream audio file from a route with the following

```
let fs = require('fs');
let a = fs.readFileSync('./assets/test.mp3', 'utf8');
get('/test/stream', ctx => header({
    'Content-Type': 'audio/mp3',
    'Content-Length': a.length
  }).send(a) )
```

### Expected outcome

Should play/ stream audio to browser

### Actual outcome

responds with 200 but doesn't load/ play/ stream audio file

### System Information

**OS:** MacOS Docker running Ubuntu

**Node Version:** v8.9.1

**Server.js Version:** 1.0.17

**Comment by franciscop** [comment]
I cannot seem to find the past issue at all, which is very strange. The problem *might* be that server will end the request with that `send()`, but I'll need further testing to confirm this since you *are* reading the whole thing in memory.

A possible alternative is to stream the file using native methods. But then you want an unterminated promise that is finished when the stream finishes. Please have a look at [the stream example here](https://github.com/franciscop/server/blob/master/examples/stream/index.js):

```js
const server = require('../../server');
const fs = require('fs');
const path = require('path');

const img = path.resolve('../../test/logo.png');

server(ctx => new Promise(resolve => {
  fs.createReadStream(img).pipe(ctx.res).on('end', resolve);
}));
```

I would guess in your situation it should be something similar. But if you want to send the headers first, then I think it might not be possible with just server and you'd have to [rely on the underlying response](https://stackoverflow.com/a/43354810/938236) a bit more (untested):

```js
const fs = require('fs');
const path = './assets/test.mp3';

const streamRoute = get('/test/stream', ctx => {
  ctx.res.setHeader('Content-Type', 'audio/mp3');
  return new Promise((resolve) => {
    fs.createReadStream(path).pipe(ctx.res).on('end', resolve);
  });
});
```

I am considering creating some `reply.stream` to make things easier, but I don't have much experience with streams.

PS, I just realized it is not documented, but there is a `reply.file()` that might fit better with what you are trying to do as well: [source code](https://github.com/franciscop/server/blob/master/reply/reply.js#L65). It follows express.js' `.sendFile()` format.

**Comment by franciscop** [comment]
Found it! It was a StackOverflow question from @hollerith, not an issue in Github. That is why I couldn't find it:

https://stackoverflow.com/questions/48763494/how-to-return-a-stream-with-server-for-nodejs-serverjs-io/49382182

@karneaud let me know if that worked please and if you have any further question

**Comment by karneaud** [comment]
Will try this out in a bit...thanks
