### ISSUE TITLE
using 3rd party socket framework

### ISSUE THREAD

**Issue by karneaud** [franciscop/server#99]
Is there anyway I can use a 3rd party socket framework either on top of or as a replacement for the abstract layer you provide?

**Comment by franciscop** [comment]
Sorry this issue is very old and I don't think you'll find it useful anymore, but for anyone coming afterwards.

Yes, you can disable the current socket implementation by passing the option `socket: false`:

```js
server({ socket: false }, ...);
```

The same [applies to any of the internal plugins](https://github.com/franciscop/server/tree/master/plugins), to load the plugins we are going first through the plugins options, which defaults to `{}` if the plugin options is not explicitly set (so if you set it to `false` it will be skipped):

```js
// [INTERNAL] filtering the plugins by their name
ctx.plugins = module.exports.plugins.filter(p => ctx.options[p.name]);
```
